stages:
  - build

container-image:
  services:
    - docker:20.10.15-dind-alpine3.15
  image: docker:20.10.15-alpine3.15
  stage: build
  before_script:
    - apk add --no-cache docker-cli-buildx
  script:
    - >-
      docker buildx build
      --file=Dockerfile
      --tag=run
      --target=run
      .
    - |-
      if [ -n "${DOCKER_USERNAME}" ] && [ -n "${DOCKER_SECRET}" ]; then
        echo "${DOCKER_SECRET}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
        docker tag run omnileads/nginx:230215.01
        docker push docker.io/omnileads/nginx:230215.01
      fi
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "oml-dev-2.0"
    - if: $CI_PIPELINE_SOURCE == "web"
