stages:
  - build

container-image:
  services:
    - docker:20.10.15-dind-alpine3.15
  image: docker:20.10.15-alpine3.15
  stage: build
  before_script:
    - apk add --no-cache docker-cli-buildx
  script:
    - >-
      docker buildx build
      --file=Dockerfile
      --tag=run
      --target=run
      .
    - |-
      if [ "${CI_COMMIT_BRANCH}" == "master-2.0" ]; then
        echo "${DOCKER_SECRET}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
        IMAGE_VERSION="$(date +%Y%m%d)-${CI_COMMIT_SHORT_SHA}"
        docker tag run omnileads/nginx:$IMAGE_VERSION
        docker push docker.io/omnileads/nginx:$IMAGE_VERSION
      else
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
        IMAGE_VERSION="$(date +%Y%m%d)-${CI_COMMIT_SHORT_SHA}"
        docker tag run freetechsolutions/nginx:$IMAGE_VERSION
        docker push docker.io/freetechsolutions/nginx:$IMAGE_VERSION
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
