services:
  api:
    build:
      target: builder
      context: ./interface/src
    container_name: omnidialer-api
    volumes:
      - ./interface/src:/app
    ports:
      - '1440:1440'
    networks:
      - network1
    stop_signal: SIGINT

  job_server:
    image: artefactual/gearmand:1.1.19.1-alpine
    container_name: gearman_job_server_1
    ports:
      - '4730:4730'
    networks:
      - network1

  worker:
    container_name: handle_campaign_worker
    build:
      target: builder
      context: ./workers/handle-campaign/src
    volumes:
      - ./workers/handle-campaign/src:/app
    networks:
      - network1

  redis:
    container_name: omnidialer-redis
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
      - BIND_IP=0.0.0.0
    networks:
      - network1
    ports:
      - 16380:6380
    image: redis:7.2.5-alpine
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - redis_omnidialer:/data

networks:
  network1:
    name: devenv_omnileads
    external: true

volumes:
  redis_omnidialer:
