# Unique identifier of the project in SonarQube
sonar.projectKey=omnileads-nginx

# Name of the project
sonar.projectName=OMniLeads NGINX

# Path to the source directories
sonar.sources=.

# Exclude build artifacts and non-source paths from analysis
sonar.exclusions=**/certs/**

# Encoding of the source files
sonar.sourceEncoding=UTF-8
