- name: Nginx installation and configuration
  hosts: prodenv-aio
  vars:
    install_prefix: /opt/omnileads
    nginx_version: '{{ lookup("env","NGINX_VERSION") }}'
    packages_url: https://fts-public-packages.s3.amazonaws.com
    nginx_package: "{{ packages_url }}/nginx/nginx-omnileads-{{ nginx_version }}.x86_64.rpm"
    certs_location: "{{ install_prefix }}/nginx_certs"
  tasks:

    # Check if Nginx package {{ nginx_version }} is installed
    - name: Check if Nginx package {{ nginx_version }} is installed
      shell: yum list installed | grep "nginx\." | awk '{print $2}' | awk -F "-" '{print $1}'
      register: nginx_installed
      changed_when: false
      tags: postinstall

    # Print message if Nginx package {{ nginx_version }} is not installed yet
    - debug: msg="Nginx package {{ nginx_version }} is not installed. Proceeding with installation."
      when: nginx_installed.stdout != nginx_version
      tags: postinstall

    # Print message if Nginx package {{ nginx_version }} is already installed
    - debug: msg="Nginx package is already installed in version {{ nginx_version }}. Skipping installation steps."
      when: nginx_installed.stdout == nginx_version
      tags: postinstall

    # Solution to issue OML-213: Backup of certs, for re-setting after Nginx installation
    - name: Backup of certs, for re-setting after Nginx installation
      when: nginx_installed.stdout == "210603.174"
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
      - { src: "{{ certs_location }}/cert.pem", dest: "/tmp/nginx-cert.pem" }
      - { src: "{{ certs_location }}/key.pem", dest: "/tmp/nginx-key.pem" }
      tags: postinstall

    # Solution to issue OML-213: Remove virtualenv package before Nginx installation
    - name: Remove virtualenv package before Nginx installation
      when: nginx_installed.stdout == "210603.174"
      command: yum remove -y virtualenv
      tags: postinstall

    # Delete previous Nginx package, before installing the latest one
    - name: Delete previous Nginx package, before installing the latest one
      yum: name=nginx state=absent
      tags: postinstall
      when: nginx_installed.stdout != nginx_version

    # Install Nginx package {{ nginx_version }}
    - name: Install Nginx package {{ nginx_version }} (from s3 source)
      yum: name={{ nginx_package }} state=latest update_cache=yes
      tags: postinstall
      retries: 3
      delay: 3
      register: s3_download
      until: s3_download is success
      when: nginx_installed.stdout != nginx_version

    # Solution to issue OML-213: Re-setting backed up certs after Nginx installation
    - name: Re-setting certs after Nginx installation
      when: nginx_installed.stdout == "210603.174"
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
      - { src: "/tmp/nginx-cert.pem", dest: "{{ certs_location }}/cert.pem" }
      - { src: "/tmp/nginx-key.pem", dest: "{{ certs_location }}/key.pem" }
      tags: postinstall

    # Copy trusted key/cert pair in Nginx location, if these files don't exist already
    - name: Copy trusted key/cert pair in Nginx location
      copy: src=certs/{{ item.src }} dest={{ item.dest }}
      with_items:
      - { src: "cert.pem", dest: "{{ certs_location }}/cert.pem" }
      - { src: "key.pem", dest: "{{ certs_location }}/key.pem" }

    # Nginx reload
    - name: Reload nginx
      systemd: name=nginx state=reloaded enabled=yes daemon_reload=yes
      tags: always
