services:
  api:
    build:
      target: builder
      context: src
    container_name: omnidialer-api
    volumes:
      - ./src:/app
    ports:
      - '1440:1440'
    networks:
      - network1
    stop_signal: SIGINT

networks:
  network1:
    name: devenv_omnileads
    external: true
